version: '3.3'

services:
  # nats:
  #   image : nats
  #   networks:
  #     - nats
  #   # restart: "always"
  #   ports:
  #     - 4222:4222

  # mongo:
  #   image : mongo:latest
  #   networks:
  #     - mongo
  #   volumes:
  #     - ./data/mongodb_data:/data/db
  #   ports:
  #     - 27017:27017

  postgres:
    build:
      context: ./database/postgre
    networks:
      - postgres
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_MULTIPLE_DATABASES=authserver,datamaster

  redis:
    image : redis:latest
    networks:
      - redis
    ports:
      - 6379:6379

networks:
  # nats:
  #   external:
  #     name: gateway
  # mongo:
  #   external:
  #     name: gateway
  postgres:
    external:
      name: gateway
  redis:
    external:
      name: gateway
