http:
  port: ${API_GATEWAY_PORT}

apiEndpoints:
  authentication:
    host: '*'
    paths: /user-login/*
    methods: ["POST","OPTIONS"]

  userlist:
    host: '*'
    paths: /user-list/*
    methods: ["GET","OPTIONS"]

  satuankerja:
    host: '*'
    paths: /satuan-kerja/*
    methods: ["GET","POST","PUT","DELETE","OPTIONS"]

  mockserver:
    host: '*'
    paths: /mock/*
    methods: ["GET","POST","PUT","DELETE","OPTIONS"]

serviceEndpoints:
  authentication:
    url: '${AUTHENTICATION_PY_SERVICE_URI}/auth/'

  userlist:
    url: '${AUTHENTICATION_PY_SERVICE_URI}/api/'

  satuankerja:
    url: '${SATUANKERJA_GO_SERVICE_URI}/api/'

  mockserver:
    url: '${MOCKSERVER_SERVICE_URI}/api/'

policies:
  - cors
  - log
  - oauth2
  - proxy
  - jwt

pipelines:
  authentication:
    apiEndpoints:
      - authentication
    policies:
      - cors:
          - action:
              allowedHeaders: '*'
      - proxy:
          - action:
              serviceEndpoint: authentication
              changeOrigin: true

  userlist:
    apiEndpoints:
      - userlist
    policies:
      - cors:
          - action:
              allowedHeaders: '*'
      - jwt:
        - action:
            secretOrPublicKey: '${SECRET_KEY:-SECRET_KEY}'
            checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: userlist
              changeOrigin: true

  satuankerja:
    apiEndpoints:
      - satuankerja
    policies:
      - cors:
          - action:
              allowedHeaders: '*'
      - jwt:
        - action:
            secretOrPublicKey: '${SECRET_KEY:-SECRET_KEY}'
            checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: satuankerja
              changeOrigin: true

  mockserver:
    apiEndpoints:
      - mockserver
    policies:
      - cors:
          - action:
              allowedHeaders: '*'
      - jwt:
        - action:
            secretOrPublicKey: '${SECRET_KEY:-SECRET_KEY}'
            checkCredentialExistence: false
      - proxy:
          - action:
              serviceEndpoint: mockserver
              changeOrigin: true
